### ISSUE TITLE
Did not work with react-router ?

### ISSUE THREAD

**Issue by easonhuang123** [HOUCe/react-quicklink-component#2]
```
<Router>
       <Quicklink>
              <App />
       </Quicklink>
</Router>
```
But it did not work, there did not have any tag likes <link rel="prefetch"/>, and I did not feel  "subsequent pages load faster"

thanks

**Comment by HOUCe** [comment]
Hey could you give more infos? Or a little demo will encouraged. 
Just the code above I am sorry that I can’t help more. 
Actually if it does work, you will find link tag through <head>

**Comment by easonhuang123** [comment]
> Hey could you give more infos? Or a little demo will encouraged.
> Just the code above I am sorry that I can’t help more.
> Actually if it does work, you will find link tag through html head

It’s the mistake I made. I put <Quicklink> on the top of the route, so it didn’t take effect. and thank you for your answer in ZhiHu too : )

**Comment by AlxGolubev** [comment]
I'm sorry guys, but I can't understand, how it actually works with react-router. As I understand changing page with react-router doesn't reload the HTML and simply replace DOM nodes in reconciliation, so how prefetching should help in that case?

**Comment by HOUCe** [comment]
> I'm sorry guys, but I can't understand, how it actually works with react-router. As I understand changing page with react-router doesn't reload the HTML and simply replace DOM nodes in reconciliation, so how prefetching should help in that case?

Hey, it won't work if you jump with React-router(simply replace DOM nodes  as you said). It will only work if your current page contains <a href="">, and jump by a tag

**Comment by AlxGolubev** [comment]
@HOUCe  thanks!
